#+setupfile: theme.org
#+title: Hello, Emacs!
#+author: Leo Cavalcante

 (staff core pf)

* Agenda

 + Minibio do Emacs

 + Porque dominar o Emacs

 + Estrutura do Emacs

 + Mão na massa 
 
* O que é o Emacs?

 + Emacs é uma *família de editores* popularmente conhecida pela sua
   *extensibilidade*.

 + O *GNU Emacs* é a variação mais conhecida e adotada.
   
 + O "Emacs" (TECO) começou a ser desenvolvido em meados dos anos 70
   no labotório de *interligência artificial* do MIT.
   
 + Já o GNU Emacs, começou a ser desenvolvido em 1984 pelo Richard
   Stallman, como uma *alternativa livre* ao Gosling Emacs (do James
   Gosling, pai do Java) que era proprietário.

 + Promoveu iniciativas como Copyleft, *software livre* e o projeto GNU,
   que são os precursores de licenças open-source.
 
 + Outras variações populares: XEmacs e SXEmacs. Não confundir com
   Doom Emacs e Spacemascs que ainda são GNU Emacs.

 + Nos anos 90 o R. Stallman ganhou ou prêmio Grace Hopper pelo
   trabalho dele com o Emacs.
   
* Domine suas ferramentas

#+begin_quote
We’ve talked before about tools being an extension of your hand.
Well, this applies to editors more than to any other software tool.
You need to be able to manipulate text as effortlessly as possible,
because text is the basic raw material of programming.
#+end_quote
—Pragmatic Programmer

* Frames, Windows & Buffers

** Frame

 + É uma representação visual do agrupamento de janelas (Windows).

 + Um Frame pode ter uma ou mais janelas.

** Window

 + É onde um Buffer é trabalhado.

 + Comparado com outros editores, visualmente a Window é como se fosse
   um painel.

** Buffer

 + É a representação do texto na memória do Emacs.

 + É o contexto onde um texto é manipulado.

* Major mode & Minor mode

** Major

 + É o como o Emacs se especializa com recursos para edição de texto
   (Buffer).

 + Cada Buffer pode ter apenas um /Major mode/ ativo por vez.

** Minor

 + São modos opcionais que alteram características específicas na
   edição de texto.

 + Os buffers podem ter zero ou mais /Minor modes/ ativos por vez.

* Showtime

+ ~C-f~ Forward (pra frente)
+ ~C-b~ Backword (pra trás)
+ ~C-n~ Next (pra próxima)
+ ~C-p~ Previous (pra anterior)

+ ~C-a~ Inicio da linha (~a~ primeira letra do alfabeto)
+ ~C-e~ Fim da linha (~e~ End)

+ ~M-<~ Início do buffer
+ ~M->~ Fim do buffer

+ ~M-f~ Forward em palavras
+ ~M-b~ Backword em palavras
- ~M-e~ End em setenças
- ~M-a~ Início de sentenças  
    
** org-mode

 * Metadados
   + ~#+title~
   + ~#+author~
   + ~#+date~
 
 * Headings & sub-headings

 * Listas

 * Tabelas

 * Blocos de código 
   #+begin_src emacs-lisp
  (print "Hello, World!")
#+end_src

** emacs-lisp

Primeiras edições no =init.el=.

  #+begin_src emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (global-display-line-numbers-mode t)
  (load-theme 'wombat t)
  (global-hl-line-mode t)
  (setq inhibit-startup-message t)

  (set-face-attribute 'default nil :family "JetBrains Mono" :height 120 :weight 'light)
  
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

#+end_src

** php-mode

Modo de destaque de sintaxe para PHP.

#+begin_src emacs-lisp
  (use-package php-mode
    :ensure t)
#+end_src

** company-mode

Modo responsável por exibir o autocomplete.

  #+begin_src emacs-lisp
  (use-package company
    :ensure t
    :config (global-company-mode t))
#+end_src

** lsp-mode

Modo do Language Server Protocol.

#+begin_src emacs-lisp
  (use-package lsp-mode
    :ensure t
    :hook (php-mode . lsp))
#+end_src

** magit

Modo que adiciona funcionalidades do Git.

#+begin_src emacs-lisp
  (use-package magit
    :ensure t)
  #+end_src
  
** treemacs

Modo responsável por exibir a estrutura de diretórios.

#+begin_src emacs-lisp
  (use-package treemacs
    :ensure t)

  (use-package treemacs-all-the-icons
    :ensure t)
#+end_src

** lsp-treemacs

Modo que adiciona funcionalidades do LSP na exibição de estruturas.

#+begin_src emacs-lisp
  (use-package lsp-treemacs
    :ensure t)
#+end_src

* Referências

+ [[https://www.gnu.org/software/emacs/][GNU Emacs]]
+ [[https://www.youtube.com/@SystemCrafters][System Crafters]]
+ [[https://www.youtube.com/@debxp][Blau Araújo (@dbexp)]]
+ [[https://www.youtube.com/@DistroTube][DistroTube]]
+ [[https://www.youtube.com/@Dunossauro][Dunossauro]]
